### PR TITLE
Embb67 coverity scan warnings

### LINKED ISSUE #67: Resolve Coverity Scan warnings
See https://scan.coverity.com/tune and https://scan.coverity.com/models for information about how to deal with false positives.

### PR DESCRIPTION
**Pull request by marcus-winter**
Fixes #67

### CODE REVIEW

**Comment by marcus-winter** [comment]
CID 1410365 and 1410366: Why not declaring "ordered" as const instead of marking the issue as intentional?

Making ordered const yields a compiler warning about the condition for while being constant.

**Comment by marcus-winter** [comment]
CID 1410372: How is memory deallocated in case of the returns in lines 330 and 338?

Not at all. Since these are checks for failing allocations there is no memory to be freed.

**Comment by tobias-schuele** [comment]
Regarding CID 1410365 and 1410366: Not clear, which "while" loop?

**Comment by marcus-winter** [comment]
If-statements in both cases. Making ordered const would yield the same warning in both cases anyway, since coverity is complaining about the conditions being constant, which is indeed intended.

**Comment by tobias-schuele** [comment]
Here's what Coverity says: "Local variable ordered is assigned only once, to a constant value, making it effectively constant throughout its scope. If this is not the intent, examine the logic to see if there is a missing assignment that would make ordered not remain constant. Otherwise, declaring ordered as const will suppress this defect."

**Comment by marcus-winter** [comment]
The warnings read:

CID 1410365 (#1 of 3): 'Constant' variable guards dead code (DEADCODE)dead_error_line: Execution cannot reach this statement:
(repeated on 2 further ifs)

CID 1410366 (#1 of 1): 'Constant' variable guards dead code (DEADCODE)dead_error_line: Execution cannot reach this statement: 

I can make ordered constant, but this will trigger a compiler warning in gcc and clang (which is why it was introduced in the first place instead of using Serial directly). In addition this will still produce dead code warnings as seen above because there is in fact dead code (which is intended this way).

**Pull request merged**
