### PR TITLE
added output for all options in cmake build script

### LINKED ISSUE #56: CMake options
The CMake files define the following options:

CMakeCommon/CreateDoxygenDocumentationTarget.cmake:  option(BUILD_DOCUMENTATION "Use Doxygen to create the HTML based API documentation" ON)
CMakeLists.txt:option(BUILD_TESTS "Specify whether tests should be built" ON)
CMakeLists.txt:option(BUILD_EXAMPLES "Specify whether examples should be built" OFF)
CMakeLists.txt:option(USE_EXCEPTIONS "Specify whether exceptions should be activated in C++" ON)
CMakeLists.txt:option(INSTALL_DOCS "Specify whether Doxygen docs should be installed" ON)
CMakeLists.txt:option(WARNINGS_ARE_ERRORS "Specify whether warnings should be treated as errors" OFF)
CMakeLists.txt:option(USE_AUTOMATIC_INITIALIZATION "Specify whether the MTAPI C++ interface, algorithms and dataflow should automatically intialize the MTAPI node if no explicit initialization is present" ON)
CMakeLists.txt:option(BUILD_OPENCL_PLUGIN "Specify whether the MTAPI OpenCL plugin should be built" OFF)

However, when running CMake, only the following options are actually listed in the output:

-- Warnings are not treated as errors (default)
   (set with command line option -DWARNINGS_ARE_ERRORS=ON/OFF)
-- MTAPI/Tasks automatic initialization enabled (default)
   (set with command line option -DUSE_AUTOMATIC_INITIALIZATION=ON/OFF)
-- Exceptions enabled (default) 
   (set with command line option -DUSE_EXCEPTIONS=ON/OFF)
-- Building tests enabled (default)
   (set with command line option -DBUILD_TESTS=ON/OFF)
-- Building examples disabled (default)
   (set with command line option -DBUILD_EXAMPLES=ON/OFF)

What about the following?

BUILD_DOCUMENTATION
INSTALL_DOCS
BUILD_OPENCL_PLUGIN

Please clarify and make consistent.

### PR DESCRIPTION
**Pull request by marcus-winter**
Fixes #56

### CODE REVIEW

**Comment by marcus-winter** [comment]
I don't know. This is how it's always been.

**Comment by tobias-schuele** [comment]
Documentation isn't built by default (which would at least require Doxygen). Please verify that CMake message matches actual settngs / build behavior.

**Comment by tobias-schuele** [comment]
Please also check that README is up to date and describes the available options.

**Comment by marcus-winter** [comment]
Documentation was built by default before I changed the defaults in the CMake-script. However if doxygen was not installed the build would only display an error message ("Doxygen is needed to build the documentation. Please install it correctly").

**Comment by marcus-winter** [comment]
BUILD_DOCUMENTATION was never mentioned in the README before. Should I add a section describing the option?

**Comment by marcus-winter** [comment]
Added all missing options to README.

**Pull request merged**
